# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-01 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functionalapplication', '0002_auto_20180301_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='message',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='user_who_favorited',
        ),
        migrations.DeleteModel(
            name='favorites',
        ),
    ]
