# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-01 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functionalapplication', '0003_auto_20180301_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cite',
            name='uploader',
        ),
        migrations.DeleteModel(
            name='cite',
        ),
    ]
